services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - "5672:5672" # RabbitMQ port
      - "15672:15672" #Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  worker: #Equivalente a pythonclient para el worker
    build: .
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: tail -f /dev/null
  mongodb:
    image: mongo:latest
    container_name: mongo_cloud
    ports:
      "27017:27017" #MongoDB Compass database port
    environment: 
      MONGO_INITDB_ROOT_USERNAME=admin
      MONGO_INITDB_ROOT_PASSWORD=admin123
  web-app:
    build: .
    ports:
      - "5001:8000"
    volumes:
      - .:/code
    depends_on:
      - mongodb
      - worker
      - rabbitmq